"""config_template.py — renders commented wrapper_config.yaml scaffolds.

Internal module; not part of the public veriflow.api surface.
Called by cmd_wrap_init after wrap_init() returns the config dict.
"""

from __future__ import annotations

from typing import Optional

import yaml

from veriflow.models.interface_profile import InterfaceProfile


def _yaml_scalar(s: str) -> str:
    """Return the YAML scalar representation of string *s*.

    Delegates to PyYAML so that empty strings, colons, and other special
    characters are quoted correctly. Strips the trailing newline yaml.safe_dump
    always adds.
    """
    dumped = yaml.safe_dump({"_": s}, default_flow_style=False, allow_unicode=True)
    # dumped: "_: value\\n" or "_: 'value'\\n"
    return dumped.split(": ", 1)[1].rstrip("\n")


def render_wrapper_config_yaml(
    config: dict,
    interface_profile: InterfaceProfile,
    ip_ports: list[tuple[str, str, Optional[int]]],
) -> str:
    """Render a human-editable wrapper_config.yaml scaffold string.

    Built as plain text (not yaml.safe_dump) to preserve field order and
    include inline comments — this file is meant to be edited by hand.

    Parameters
    ----------
    config
        Dict as returned by api.wrap_init (schema keys only; "detected_ports"
        key is ignored if present).
    interface_profile
        The resolved InterfaceProfile for the interface declared in config.
    ip_ports
        3-tuples (name, direction, width | None) from extract_ports.
    """
    lines: list[str] = []

    # ── Comment header — interface port reference ────────────────────────────
    lines.append("# Generated by veriflow wrap init")
    lines.append(f"# Interface: {interface_profile.name}")
    lines.append("#")
    lines.append("# Interface ports (fill in the 'ports' section below):")
    for p in interface_profile.ports:
        lines.append(f"#   {p.name}: {p.direction}, {p.width}")
    lines.append("")

    # ── interface_name ───────────────────────────────────────────────────────
    lines.append(f"interface_name: {_yaml_scalar(config['interface_name'])}")
    lines.append("")

    # ── metadata ─────────────────────────────────────────────────────────────
    meta: dict = config.get("metadata") or {}
    lines.append("metadata:")
    for key in ("name", "author", "description", "version"):
        lines.append(f"  {key}: {_yaml_scalar(str(meta.get(key, '')))}")
    lines.append("")

    # ── design ───────────────────────────────────────────────────────────────
    design: dict = config.get("design") or {}
    lines.append("design:")
    lines.append(f"  top_module: {_yaml_scalar(str(design.get('top_module', '')))}")
    lines.append("  rtl_sources:")
    for src in (design.get("rtl_sources") or []):
        lines.append(f"    - {_yaml_scalar(str(src))}")
    lines.append("")

    # ── wrapper_name ─────────────────────────────────────────────────────────
    lines.append(f"wrapper_name: {_yaml_scalar(str(config.get('wrapper_name', '')))}")
    lines.append("")

    # ── ports — one line per IP port; filled value if present, else empty ──
    # When config["ports"][name] is not None (wizard already mapped it),
    # write the value on the same line so the file is immediately usable.
    # (N14)
    ports_dict: dict = config.get("ports") or {}
    lines.append("ports:")
    if ip_ports:
        max_name_len = max(len(name) for name, _, _ in ip_ports)
        for name, direction, width in ip_ports:
            width_str = str(width) if width is not None else "?"
            pad = " " * (max_name_len - len(name))
            val = ports_dict.get(name)
            if val is not None:
                lines.append(
                    f"  {name}:{pad} {_yaml_scalar(str(val))}  # {direction}, {width_str}"
                )
            else:
                lines.append(f"  {name}:{pad}  # {direction}, {width_str}")
    else:
        lines.append("  # (no ports detected in top module)")
    lines.append("")

    return "\n".join(lines)
